### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by EnqiBaiCN2000** [HKUST-Aerial-Robotics/FC-Planner#5]
I have encountered such a compilation error. How can I solve it? Thank you for your guidance
[ 66%] Generating C++ code from quadrotor_msgs/PolynomialTrajGroup.msg
[ 70%] Built target plan_env
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:195: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/Serial.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/Serial.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/Serial.h”
make[2]: *** 正在等待未完成的任务....
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
Traceback (most recent call last):
AttributeError:   File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
'module' object has no attribute 'RAW_OPT'
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:102: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/Gains.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/Gains.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/Gains.h”
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:117: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/Odometry.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/Odometry.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/Odometry.h”
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:162: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PolynomialTrajectory.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PolynomialTrajectory.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PolynomialTrajectory.h”
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:216: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/TakeoffLand.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/TakeoffLand.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/TakeoffLand.h”
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError    : sys.argv, msg_template_map, srv_template_map)
'module' object has no attribute 'RAW_OPT'  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options

    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:171: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PositionCommand.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PositionCommand.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PositionCommand.h”
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:210: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/TRPYCommand.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/TRPYCommand.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/TRPYCommand.h”
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:202: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/StatusData.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/StatusData.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/StatusData.h”
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:147: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PolynomialTraj.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PolynomialTraj.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PolynomialTraj.h”
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:126: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/OutputData.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/OutputData.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/OutputData.h”
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:139: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PolynomialMatrix.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PolynomialMatrix.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PolynomialMatrix.h”
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:188: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/SO3Command.h' failed
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/SO3Command.h] Error 1
    search_path)
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/SO3Command.h”
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:133: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PPROutputData.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PPROutputData.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PPROutputData.h”
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:155: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PolynomialTrajGroup.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PolynomialTrajGroup.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/PolynomialTrajGroup.h”
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:178: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/Px4ctrlDebug.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/Px4ctrlDebug.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/Px4ctrlDebug.h”
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:90: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/AuxCommand.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/AuxCommand.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/AuxCommand.h”
Traceback (most recent call last):
  File "/opt/ros/melodic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 50, in <module>
    sys.argv, msg_template_map, srv_template_map)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 99, in _generate_msg_from_file
    search_path)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'RAW_OPT'
FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/build.make:96: recipe for target '/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/Corrections.h' failed
make[2]: *** [/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/Corrections.h] Error 1
make[2]: *** 正在删除文件“/home/baienqi/catkin_ws2/devel/include/quadrotor_msgs/Corrections.h”
CMakeFiles/Makefile2:1864: recipe for target 'FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/all' failed
make[1]: *** [FC-Planner/FC-Planner/src/quadrotor_msgs/CMakeFiles/quadrotor_msgs_generate_messages_cpp.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 72%] Built target active_perception
[ 74%] Built target path_searching
In file included from /home/baienqi/catkin_ws2/src/FC-Planner/FC-Planner/src/rosa/include/rosa/rosa_main.h:24:0,
                 from /home/baienqi/catkin_ws2/src/FC-Planner/FC-Planner/src/viewpoint_manager/include/viewpoint_manager/skeleton_viewpoint.h:24,
                 from /home/baienqi/catkin_ws2/src/FC-Planner/FC-Planner/src/viewpoint_manager/src/skeleton_viewpoint.cpp:21:
/home/baienqi/catkin_ws2/src/FC-Planner/FC-Planner/src/traj_utils/include/traj_utils/planning_visualization.h:36:10: fatal error: quadrotor_msgs/PolynomialTraj.h: 没有那个文件或目录
 #include <quadrotor_msgs/PolynomialTraj.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
FC-Planner/FC-Planner/src/viewpoint_manager/CMakeFiles/skeleton_viewpoint.dir/build.make:75: recipe for target 'FC-Planner/FC-Planner/src/viewpoint_manager/CMakeFiles/skeleton_viewpoint.dir/src/skeleton_viewpoint.cpp.o' failed
make[2]: *** [FC-Planner/FC-Planner/src/viewpoint_manager/CMakeFiles/skeleton_viewpoint.dir/src/skeleton_viewpoint.cpp.o] Error 1
CMakeFiles/Makefile2:2700: recipe for target 'FC-Planner/FC-Planner/src/viewpoint_manager/CMakeFiles/skeleton_viewpoint.dir/all' failed
make[1]: *** [FC-Planner/FC-Planner/src/viewpoint_manager/CMakeFiles/skeleton_viewpoint.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j20 -l20" failed

**Comment by Chen-Albert-FENG** [comment]
Please refer to https://github.com/HKUST-Aerial-Robotics/FC-Planner/issues/6.
